Статья:
  Торговая ДЗ:
    - Готовая продукция
    - Авансы полученные(металлы)   # USD
  
  Прочая ДЗ:
    - Материалы
  
  Авансы выданные и расходы будущих периодов:
    - Материалы
    - Прочие налоги к возмещению ST  # lag2
    - Прочие налоговые обязательства  # lag2
  
  Прочие налоги к возмещению ST:
    - Материалы
    - Готовая продукция
    - Прочие налоговые обязательства
    - НЗП
    - Торговая КЗ
  
  Прочие налоговые обязательства:
    - Готовая продукция
    - Прочая ДЗ
    - Материалы
    - Задолженность перед персоналом
    - НЗП
    - Торговая КЗ
  
  Задолженность перед персоналом:
    - Краткосрочный резерв по премиям
    - Резерв по неиспользованным отпускам
  
  Резерв по неиспользованным отпускам:
    - Краткосрочный резерв по премиям
    - Задолженность перед персоналом
  
  Краткосрочный резерв по премиям:
    - Задолженность перед персоналом
    - Резерв по неиспользованным отпускам
  
  Прочее:
    - Краткосрочный резерв по премиям
    - Задолженность перед персоналом
  
  Кредиторская задлолженность по ОС:
    - Курс
  
  Авансы полученные:
    - Материалы
  
  Авансы полученные(металлы):
    - Готовая продукция
    - Торговая ДЗ
  
  Торговая КЗ:
    - Авансы выданные и расходы будущих периодов
    - Материалы
    - Авансовые платежи по налогу на прибыль
    - Прочие налоги к возмещению ST
    - Прочие налоговые обязательства

  Авансовые платежи по налогу на прибыль: []

  Обязательства по налогу на прибыль: []

  ЧОК (нормализовано на расчеты с акционерами):
    - Торговая ДЗ
    - Прочая ДЗ
    - Авансы выданные и расходы будущих периодов
    - Прочие налоги к возмещению ST
    - Прочие налоговые обязательства
    - Задолженность перед персоналом
    - Резерв по неиспользованным отпускам
    - Краткосрочный резерв по премиям
    - Прочее
    - Кредиторская задлолженность по ОС
    - Авансы полученные
    - Авансы полученные(металлы)
    - Торговая КЗ
    - Авансовые платежи по налогу на прибыль
    - Обязательства по налогу на прибыль
    - Курс


Фичи в Статьях для LAG:
  Авансовые платежи по налогу на прибыль:
    Авансовые платежи по налогу на прибыль: 1
  Обязательства по налогу на прибыль:
    Обязательства по налогу на прибыль: 1
  Авансы выданные и расходы будущих периодов:
    Прочие налоги к возмещению ST: 2
    Прочие налоговые обязательства: 2

Фичи в Статьях для USD:
  Торговая ДЗ:
    - Авансы полученные(металлы)
    
Статьи для предикта в USD:
  - Торговая ДЗ

Статьи для раскладывания даты на месяц и год:
  - Авансовые платежи по налогу на прибыль
  - Обязательства по налогу на прибыль


DATE_COLUMN: Дата
RATE_COLUMN: Курс
item_id: INDIVIDUAL
factor: INDIVIDUAL
metric_for_training: MAE
PREDICT_BASE: True
PREDICT_BASEplus: False

models_to_use:
  NaiveModel: {}
  SeasonalNaiveModel: {}
  AverageModel: {}
  SeasonalAverageModel: {}
  ZeroModel: {}
  AutoARIMAModel: {}
  AutoETSModel: {}
  ThetaModel: {}
  CrostonModel: {}
  NPTSModel: {}
  DeepARModel: {}
  PatchTSTModel: {}
  TemporalFusionTransformerModel: {}
  TiDEModel: {}
  DirectTabularModel: {}
  RecursiveTabularModel: {}
  Chronos:
    - model_path: pretrained_models/chronos-bolt-base
      ag_args:
        name_suffix: ZeroShot
    - model_path: pretrained_models/chronos-bolt-small
      ag_args:
        name_suffix: ZeroShot
    - model_path: pretrained_models/chronos-bolt-small
      fine_tune: true
      ag_args:
        name_suffix: FineTuned
TABPFNMIX_model:
  TABPFNMIX:
    model_path_regressor: 'pretrained_models/tabpfn-mix-1.0-regressor'
    n_ensembles: 1
    max_epochs: 30

    
model_article:
  Торговая ДЗ:
    model: stacking_rfr
    pipeline: base+
  Прочая ДЗ:
    model: ml_tabular
    pipeline: base+
  Авансы выданные и расходы будущих периодов:
    model: ml_tabular
    pipeline: base+
  Прочие налоги к возмещению ST:
    model: autoarima
    pipeline: base
  Прочие налоговые обязательства:
    model: autoarima
    pipeline: base
  Задолженность перед персоналом:
    model: tft
    pipeline: base
  Резерв по неиспользованным отпускам:
    model: linreg9_with_bias
    pipeline: base+
  Краткосрочный резерв по премиям:
    model: autoarima
    pipeline: base
  Прочее:
    model: naive
    pipeline: base
  Кредиторская задлолженность по ОС:
    model: TS_ML
    pipeline: base
  Авансы полученные:
    model: chronos_base
    pipeline: base
  Авансы полученные(металлы):
    model: svm6
    pipeline: base+
  Торговая КЗ:
    model: tabpfnmix
    pipeline: base+
  Авансовые платежи по налогу на прибыль:
    model: stacking_rfr
    pipeline: base
  Обязательства по налогу на прибыль:
    model: naive
    pipeline: base
  ЧОК (нормализовано на расчеты с акционерами):
    model: stacking_rfr
    pipeline: base

model_article_reserved_model:
  Торговая ДЗ:
    model: svm9
    pipeline: base+
  Прочая ДЗ:
    model: linreg6_no_bias
    pipeline: base+
  Авансы выданные и расходы будущих периодов:
    model: svm6
    pipeline: base+
  Прочие налоги к возмещению ST:
    model: tft
    pipeline: base+
  Прочие налоговые обязательства:
    model: svm12
    pipeline: base+
  Задолженность перед персоналом:
    model: linreg9_with_bias
    pipeline: base+
  Резерв по неиспользованным отпускам:
    model: autoarima
    pipeline: base+
  Краткосрочный резерв по премиям:
    model: svm6
    pipeline: base+
  Прочее:
    model: chronos_base
    pipeline: base+
  Кредиторская задлолженность по ОС:
    model: patchtst
    pipeline: base+
  Авансы полученные:
    model: linreg12_no_bias
    pipeline: base+
  Авансы полученные(металлы):
    model: ts_ml
    pipeline: base+
  Торговая КЗ:
    model: linreg6_with_bias
    pipeline: base+
  Авансовые платежи по налогу на прибыль:
    model: linreg9_no_bias
    pipeline: base+
  Обязательства по налогу на прибыль:
    model: naive
    pipeline: base+
  ЧОК (нормализовано на расчеты с акционерами):
    model: stacking_rfr
    pipeline: base+


bullet_chart_limits:
  RUB:
    diff_min: -10
    diff_max: 10
    deviation_min: -5
    deviation_max: 5
  USD:
    diff_min: -0.142
    diff_max: 0.142
    deviation_min: -5
    deviation_max: 5

Налоги:
  НДС:
    - 'E110000 - ПАО "ГМК "Норильский никель"'
    - 'E120200 - АО "Кольская ГМК"'
    - 'Прочие компании'
  Налог на прибыль:
    - 'E110000 - ПАО "ГМК "Норильский никель"'
    - 'E120200 - АО "Кольская ГМК"'
    - 'E133700 - ООО "ГРК "Быстринское"'
    - 'Прочие компании'
  НДПИ:
    - 'E110000 - ПАО "ГМК "Норильский никель"'
    - 'Прочие компании'
  НВОС:
    - 'Прочие компании'
  НДФЛ:
    - 'Прочие компании'
  Прочее:
    - 'Прочие компании'
  Страховые взносы:
    - 'Прочие компании'